Repository ThisDotE/InnerJoinUs, pull requests merged in 2024-03, with the labels that each got.

#1 [Feature] Eureka main Server 구축
  innerjoinus-server-source/src/main/resources/application.properties
  innerjoinus-server-source/src/main/resources/application.yml
Labels: enhancement

#2 [Feature] Gateway 구축
  innerjoinus-gateway-source/build.gradle
  innerjoinus-gateway-source/src/main/java/org/thisdote/gateway/filter/AuthorizationHeaderFilter.java
  innerjoinus-gateway-source/src/main/resources/application.properties
  innerjoinus-gateway-source/src/main/resources/application.yml
Labels: enhancement

#6 [Feature/article] 게시글 삭제 및 초기 환경 구축
  innerjoinus-article-reply-source/build.gradle
  innerjoinus-article-reply-source/src/main/java/org/thisdote/articlereply/InnerjoinusArticleReplySourceApplication.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/InnerjoinusArticleReplySourceApplication.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/aggregate/ArticleEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/controller/ArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/repository/CommandArticleRepository.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/RequestArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/RequestDeleteArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/RequestModifyArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/RequestRegistArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/ResponseDeleteArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/ResponseModifyArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/ResponseRegistArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/dto/ArticleDTO.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/aggregate/ArticleCategory.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/aggregate/SearchCriteriaEnum.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/controller/ArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/Article.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/configuration/MybatisConfiguration.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/aggregate/ReplyCommandEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/controller/ReplyCommandController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/repository/ReplyCommandRepository.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/service/ReplyCommandService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/vo/ReplyCommandVo.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/dto/ReplyDTO.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/aggregate/ReplyQueryEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/controller/ReplyQueryController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/repository/ReplyMapper.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/service/ReplyQueryService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/vo/ReplyQueryVo.java
  innerjoinus-article-reply-source/src/main/resources/application.properties
  innerjoinus-article-reply-source/src/main/resources/application.yml
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/ArticleMapper.xml
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/reply/ReplyMapper.xml
  innerjoinus-article-reply-source/src/test/java/org/thisdote/articlereply/InnerjoinusArticleReplySourceApplicationTestsEntity.java
  innerjoinus-studygroup-source/build.gradle
  innerjoinus-user-client-source/src/main/java/org/thisdote/user/InnerjoinusUserClientSourceApplication.java
Labels: enhancement

#12 [Feature/reply] 댓글 생성 기능 구현
  innerjoinus-article-reply-source/build.gradle
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/aggregate/ReplyCommandEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/controller/ReplyCommandController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/service/ReplyCommandService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/service/ReplyCommandServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/vo/RequestRegistReply.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/vo/ResponseRegistReply.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/dto/ReplyDTO.java
  innerjoinus-article-reply-source/src/main/resources/application.yml
Labels: enhancement

#7 [Feature/studygroup-member] 스터디 멤버(스터디장, 스터디원) 전체 조회 기능 구현
  innerjoinus-studygroup-source/build.gradle
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/InnerjoinusStudygroupSourceApplication.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/config/MybatisConfiguration.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/client/StudyGroupMemberServiceClient.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/controller/StudyGroupMemberCommandController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/entity/StudyGroupMemberEntity.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/repository/StudyGroupMemberCommandRepository.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/service/StudyGroupMemberCommandService.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/dto/StudyGroupMemberDTO.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/controller/StudyGroupMemberController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/repository/StudyGroupMemberMapper.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/service/StudyGroupMemberService.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/vo/ResponseStudyGroupMember.java
  innerjoinus-studygroup-source/src/main/resources/application.properties
  innerjoinus-studygroup-source/src/main/resources/application.yml
  innerjoinus-studygroup-source/src/main/resources/org/thisdote/innerjoinus/studygroup_member/query/repository/StudyGroupMemberMapper.xml
Labels: enhancement

#14 [Feature] 회원 도메인 관련 기능 코드 추가
  innerjoinus-user-client-source/build.gradle
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/InnerjoinusUserClientSourceApplication.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/controller/UserCommandController.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/entity/UserEntity.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/repository/UserRepository.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/service/UserCommandService.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/service/UserCommandServiceImpl.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/dto/StudyGroupMemberDTO.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/dto/UserDTO.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/config/MyBatisConfig.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/controller/UserQueryController.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/repository/UserMapper.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/service/UserQueryService.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/service/UserQueryServiceImpl.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/vo/RequestUser.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/vo/ResponseUser.java
  innerjoinus-user-client-source/src/main/resources/application.properties
  innerjoinus-user-client-source/src/main/resources/application.yml
  innerjoinus-user-client-source/src/main/resources/org/thisdote/innerjoinus/user/query/repository/UserMapper.xml
Labels: enhancement

#15 [Feature/Article] 조회 구현
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/aggregate/ArticleEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/controller/CommandArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/controller/ArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/ResponseArticle.java
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.xml
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/reply/query/repository/ReplyMapper.xml
Labels: enhancement

#16 [Feature/Article] User 코드 이용한 Article 조회
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/controller/ArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/ResponseArticleByUser.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/ResponseQuestionArticle.java
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.xml
Labels: enhancement

#18 [Feature] Service Client 연동 설정
  innerjoinus-gateway-source/src/main/resources/application.yml
Labels: enhancement

#21 [Feature/reply] 댓글 삭제 기능 구현
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/controller/ReplyCommandController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/service/ReplyCommandService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/service/ReplyCommandServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/vo/RequestDeleteReply.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/vo/ResponseDeleteReply.java
Labels: enhancement

#25 [Feature/studygroup member] 스터디 멤버 (스터디장, 스터디원) 추가, 수정 기능 구현
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/controller/StudyGroupMemberCommandController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/service/StudyGroupMemberCommandService.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/vo/RequestModifyStudyGroupMember.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/vo/RequestStudyGroupMember.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/vo/ResponseModifyStudyGroupMember.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/vo/ResponseStudyGroupMember.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/dto/StudyGroupMemberDTO.java
Labels: enhancement

#33 [Feature/reply] 댓글 수정 기능 구현
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/service/ReplyCommandService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/service/ReplyCommandServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/vo/RequestModifyReply.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/vo/ResponseModifyReply.java
Labels: enhancement

#35 [Feature/Article] Dynamic Query 조회 구현
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/RequestArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/controller/ArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/Article.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/RequestSelectEnum.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/ResponseSelectEnum.java
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.xml
Labels: enhancement

#41 [Feature/Article] 코드 정리
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/controller/CommandArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/aggregate/ArticleCategory.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.xml
Labels: Improvement

#53 [Feature] 스프링 시큐리티 적용
  innerjoinus-gateway-source/src/main/java/org/thisdote/gateway/filter/AuthorizationHeaderFilter.java
  innerjoinus-gateway-source/src/main/resources/application.yml
  innerjoinus-user-client-source/build.gradle
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/InnerjoinusUserClientSourceApplication.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/controller/UserCommandController.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/entity/UserEntity.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/repository/UserRepository.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/controller/UserQueryController.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/repository/UserMapper.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/service/UserQueryService.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/service/UserQueryServiceImpl.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/security/AuthenticationFilter.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/security/JwtFilter.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/security/JwtUtil.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/security/WebSecurity.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/vo/RequestLogin.java
  innerjoinus-user-client-source/src/main/resources/org/thisdote/innerjoinus/user/query/repository/UserMapper.xml
Labels: enhancement

#58 [feature/refactor] Refactoring request mapping paths
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/controller/CommandArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/controller/ArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/client/UserClient.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/controller/ReplyCommandController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/controller/ReplyQueryController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup/command/controller/StudyGroupCommandController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup/query/controller/StudyGroupQueryController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/client/UserClient.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/command/controller/StudyGroupMemberCommandController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/controller/StudyGroupMemberController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/service/StudyGroupMemberService.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/client/ArticleReplyServiceClient.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/command/controller/UserCommandController.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/controller/UserQueryController.java
Labels: bug, enhancement

#59 [Feature] Refactoring
  innerjoinus-article-reply-source/hs_err_pid18372.log
  innerjoinus-article-reply-source/hs_err_pid22700.log
  innerjoinus-article-reply-source/replay_pid18372.log
  innerjoinus-article-reply-source/replay_pid22700.log
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/aggregate/ArticleEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/controller/CommandArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/RequestRegistArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/ResponseArticleUser.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/ResponseDeleteArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/ResponseModifyArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/dto/ArticleDTO.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/vo/ResponseArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/command/controller/ReplyCommandController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/dto/ReplyDTO.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/repository/ReplyQueryRepository.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/service/ReplyQueryService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reply/query/service/ReplyQueryServiceImpl.java
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.xml
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/config/MybatisConfiguration.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup/command/controller/StudyGroupCommandController.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup/command/entity/StudyGroupEntity.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup/command/service/StudyGroupCommandService.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup/command/service/StudyGroupCommandServiceImpl.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/client/UserClient.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/query/service/UserQueryServiceImpl.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/security/JwtUtil.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/security/WebSecurity.java
Labels: bug, enhancement

#63 [Feature] Increase View Count
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/aggregate/ArticleEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/controller/CommandArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/controller/ArticleController.java
Labels: enhancement

#68 [Feature/refactoring] Main 화면 인기 게시글
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/service/CommandArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/controller/ArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.xml
Labels: enhancement

#69 [Feature/article-reply] 게시글별 달린 실제 댓글 수 count
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/command/vo/ResponseUser.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/article/query/service/ArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/configuration/CORSConfiguration.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedarticle/command/aggregate/CommandReportedArticleEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedarticle/command/controller/CommandReportedArticleController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedarticle/command/repository/CommandReportedArticleRepository.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedarticle/command/service/CommandReportedArticleService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedarticle/command/service/CommandReportedArticleServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedarticle/command/vo/Response.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedarticle/dto/ReportedArticle.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedreply/command/aggregate/CommandReportedReplyEntity.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedreply/command/controller/CommandReportedReplyController.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedreply/command/repository/CommandReportedReplyRepository.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedreply/command/service/CommandReportedReplyService.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedreply/command/service/CommandReportedReplyServiceImpl.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedreply/command/vo/Response.java
  innerjoinus-article-reply-source/src/main/java/org/thisdote/innerjoinus/articlereply/reportedreply/dto/ArticleReplyDTO.java
  innerjoinus-article-reply-source/src/main/resources/org/thisdote/innerjoinus/articlereply/article/query/repository/ArticleMapper.xml
  innerjoinus-gateway-source/src/main/resources/application.yml
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/command/controller/CommandInquiryController.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/command/entity/CommandInquiryEntity.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/command/repository/CommandInquiryRepository.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/command/service/CommandInquiryService.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/command/service/CommandInquiryServiceImpl.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/dto/InquiryDTO.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/aggregate/QueryInquiryEntity.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/config/MybatisConfiguration.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/controller/QueryInquiryController.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/repository/InquiryMapper.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/repository/QueryInquiryRepository.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/service/QueryInquiryService.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/service/QueryInquiryServiceImpl.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/inquiry/query/vo/ResponseQueryInquiry.java
  innerjoinus-user-client-source/src/main/java/org/thisdote/innerjoinus/user/security/JwtUtil.java
Labels: enhancement

#70 [Feature/feign studygroup member] select by studygroup member Id
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/repository/StudyGroupMemberMapper.java
  innerjoinus-studygroup-source/src/main/java/org/thisdote/innerjoinus/studygroup_member/query/vo/ResponseSelectStudyGroupById.java
Labels: enhancement
